### PR TITLE
CodeTest2

### PR DESCRIPTION
**Pull request by dalenae**

### CODE REVIEW

**Review by ahsansiddiki — COMMENTED** [review]
I don't see any code here for HW#2. Do you wanna delete this PR? I'll look into your Mid term code from the original PR.

**Comment by dalenae** [comment]
Yes should I delete it or can you?

**Comment by ahsansiddiki** [comment]
I closed this PR.

**Comment by dalenae** [comment]
Okay I now see my mistake, I wasn't switching branches before starting
Homeworks. The pull request I just sent has my Code Test, HW2 and 3 on
there. Moving forward I'll make sure to switch to new branches before
submitting pull requests.

**Pull request closed without merging**
